spring:
  application:
    name: springboot-web

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
#    static-path-pattern: /static/**
    servlet:
      load-on-startup: 1

  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8

  servlet:
    multipart:
      max-file-size: 31457280
      max-request-size: 31457280

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.129.2/springboot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: portal
    password: portal@300!**
    druid:
      initial-size: 150
      min-idle: 150
      max-active: 1000
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      keep-alive: true
#      remove-abandoned: false
#      remove-abandoned-timeout: 100
#      filters: stat

# redis配置(兼容三种方式的redis服务端部署)，如果是集群方式，用分号分隔配置多个节点即可
redis:
  server-nodes: 172.16.32.117:6379
  password: spider@1314
  jedis-pool:
    max-total: 5



#shiro:
#  sessionManager:
#    cookie:
#      name: pjsid
##      secure: true
#    sessionIdUrlRewritingEnabled: false

#  threadpool:
#    corePoolSize: 32
#    maxPoolSize: 100
#    keepAliveTime: 60
#    queueCapacity: 100

server:
  tomcat:
    max-threads: 1000
    min-spare-threads: 30
    uri-encoding: UTF-8
    basedir: /u01/tomcat_web_temp
    port-header: x-forwarded-port
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
#    internal-proxies: 10\.\d{1,3}\.\d{1,3}\.\d{1,3}|172\.\d{1,3}\.\d{1,3}\.\d{1,3}|192\.\d{1,3}\.\d{1,3}\.\d{1,3}
    internal-proxies: \d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}
  forwardHeadersStrategy: native
#  use-forward-headers: true
  port: 8001
  address: 0.0.0.0
  servlet:
    context-path: /

logging:
  config: classpath:log4j.xml
  level:
    com.meiya.springboot.mapper: debug